manipulation/transformations/python/index.md
It is a common practice to make scripts like this:
```python
def main():
print("Hello keboola!")
if __name__ == '__main__":
main()
```
However this did not work for my Python transformation, so I had to do:
```python
def main():
print("Hello keboola!")
main()
```
I guess it is because 
a) the script `/data/script.py` is only imported (thus`__name__` is not `'__main__'`)
b) running `eval()` on the file contents of `script.py`
c) the mistake is on my side
If it's `a`, or `b` I suppose it is wort it to clarify this in the docs. If it is `c` I am sorry for confusion (and I would be curious what could be the issue!)
=> clarify how the script is ran

extractors/storage/ftp/index.md
Doplnil jsem, že pro glob syntax v podadresářích musí FTP server podporovat recursivní listování.
=> Senteces about recursive listing support

extractors/marketing-sales/google-analytics/index.md
Replaced old callback urls with new ones in
https://help.keboola.com/extractors/marketing-sales/google-analytics/#custom-oauth-credentials
=> fix (google-analytics): new OAuth callback urls for custom authorization

README.md, components/applications/index.md
Nic jako **Keboola Connection App Store** nemáme, viz slack https://keboola.slack.com/archives/C0A5ZK1LY/p1596127474000800
=> Rename app store

components/extractors/marketing-sales/google-analytics/index.md
Custom Authorization v GA extraktore, treba zapnut nie len `Google Analytics Reporting API` ale aj `Google Analytics API` aby to fungovalo pre Multi-Channel Funnels (MCF) API.
https://keboola.slack.com/archives/C02CFRNRD/p1602660570011800
=> fix (ex-google-analytics): custom authorization with MCF API

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
Part of https://keboola.atlassian.net/browse/SRE-2035
Přidání nových outbound IPs nové EKS infra. Z těchno IPs začnou komunikovat až joby nové queue. Updatujeme dopředu a hodíme i do changelogu.
A vyhodil jsem z těch jsonů `ap-southeast-2` který už je vypnutý. 
Diff vypadá srozumitelněji po commitech...
=> AWS - New outbound IPs for consolidated accounts

components/extractors/database/mongodb/mapping.md
Based on this ticket: https://keboola.zendesk.com/agent/tickets/20880
I want to add example of mapping array with nester properties to a single output table. The same way it's possible in the generic ex.
=> Add single table output example for arrays

components/extractors/other/google-search-console/index.md
Hi the link to the docs had to be changed after they are no longer available. The code also uses the most up to date API.
=> update links to documentation

components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
Related to: https://keboola.atlassian.net/browse/SRE-3256
Fixní IPs pro legacy storage workery, původně jsem si říkal že nechám jen v internal docs ale nakonec abych to předal exasol mi to přijde lepší takhle. Jakmile zkonsolidujeme connection tak se tyhle IPs zas odmažou.
Funkční firewall:
https://connection.eu-central-1.keboola.com/admin/projects/3191/queue/389636917
=> New legacy storage worker ips

components/extractors/other/telemetry-data/telemetry-data.md
Do telemetry data ex docs přidávám informaci o systémových dst_ slupcích a informaci o tom, jak čerstvá data je možné použitím získat.
=> Telemetry: Adding info about dst_ columns and data recency

components/extractors/other/telemetry-data/telemetry-data.md
Tabulka kbc_job v telemetrii byla rozšířena o dva nové sloupce:
* error_type
* error_message
Přidávám jejich popis do docs.
=> Adding new columns to kbc_job telemetry table

_data/navigation.yml, templates/datahub/datahub.md
- updating nav to add GA to Templates (to make it public - https://help.keboola.com/templates/google-analytics/)
- fixing links in Templates/DataHub
=> Add ga to navigation

assets/css/style.scss
Jira issue: [UT-332](https://keboola.atlassian.net/browse/UT-332)
Relates to: https://github.com/keboola/developers-docs/pull/234
Fix overflowing content on mobile;
- Allow automatic overflow on main wrapper
- Limit width of all images to width of its parents
[UT-332]: https://keboola.atlassian.net/browse/UT-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix content overflowing

management/project/limits/index.md
Based on request from Jakub Stracina, I'm changing docs about extractors billing. Our current default pricing is 2 PPU/h and leaving "Per contract" there would be confusing for new clients and it would also allow unnecessary discussions about final credits amount.
=> Change extractors billing in pricing

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
FIXES: https://keboola.atlassian.net/browse/ST-381
Aktualizace IP adres a pofixování současného stavu:
- Odstranění nepoužívanách IPS, nově se pak přidávají jako odchozí pro QV2
- Sjednoceni json souborů - nebyly stejné
- Oddelění IP adres pro legacy QV1 do samotných sekcí
- Odstraněný syrup pro Azure NE
- Označení email outbound IP adres a v json souborech uvedeno jako `email-delivery` služba
- Přidání nových IP adres, zatím přes ně nejde traffic. Bude k tomu blog post, validace, CSM, emaily atd... Kdo teď ale bude nově nastavovat pravidla firewall rovnou už nastaví všechny a bude to mít ready.
Zkouknou by mohlo jít lépe po commitech. Ty samotné IP https://keboola.atlassian.net/wiki/spaces/KB/pages/2880503825/Outbound+IPs jsem několikrát kontroloval tady i oproti AWS a mělo by to být ok. …
=> IPs update

transformations/python-plain/index.md, transformations/python/index.md
https://keboola.atlassian.net/browse/PST-374
Zkusil jsme par random hledani a nasle jen tyhle dva vyskyty. V developer docs jsme nenasel nic.
Zvazoval jsme jeste ten link, co si zminoval v issue, ale nakonec jsem se rozhodl ho tma nedavat:
* je ruzny pro kazdy stack a i kdyz je to ted stejne, do budoucna se ty verze muzou lisit (tyicky treba pro single-tenanty)
* vycist z toho JSON co hledas neni na prvni dobrou uplne snadne a nez to tam popisovat, je IMHO jednodussi se podivat nomrlane do projektu, co vidis v UI
=> PST-374 Remove Python version from docs

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): -
Connection PR due CT-918 : https://github.com/keboola/connection/pull/4294
Changes:
- added 
- `auditLog.spc.account.created`
- `auditLog.payg.topup.try`, `auditLog.payg.topup.updated` becaus Zajca forgot them
- removed
- `auditLog.payAsYouGo.marketingData` because we don't send it anymore
---
=> Add spc events, add payg events, remove marketingData

_data/navigation.yml, components/extractors/marketing-sales/google-analytics/index.md
Customers are constantly asking if GA extractor supports GA4. IMO no average user knows what Data API versus Reporting API v4 means and how it translates to GA4 or UA.
Changes:
- Mention GA4 in various places so it comes up in search
=> Mention GA4 in GA component

components/extractors/communication/email-imap/index.md
Adding skip-lines processor to the csv file processing example because the create file manifest processor is stupid and does not drop headers for sliced files when from:header is used.
=> fix processors example to remove header from data

management/project/limits/index.md
For some reason, credits for Large DS backend have shown wrong value in the docs. I'm updating it to 6PPU/h to match the telemetry/billing scripts.
=> Updating PPU for Large DS backend to correct number

components/extractors/other/telemetry-data/telemetry-data.md
Two new tables containing data about input/output tables of the KBC jobs.
Changes:
- table `kbc_job_input_table` added
- table `kbc_job_output_table` added
---
=> Adding new table to activity center mode of telemetry ex

_layouts/default.html
Všechny H2 atd na stránce mají ID ale hlavní ID ne. Tak fajn to přidat.  Mě to pomůže v PoC na dokumentaci přímo zobrazenou v UI že tam budu moci přidat anchor.
=> Přidaný ID k hlavnímu nadpisu.

storage/byodb.md
Jira issue(s): https://keboola.atlassian.net/browse/PROOF-152
Changes:
-
---
z https://keboola.atlassian.net/browse/BIG-101 jsem to vytahl i do public docs
=> Add BQ limits

tutorial/manipulate/index.md
Relates to [SUPPORT-5541](https://keboola.atlassian.net/browse/SUPPORT-5541?atlOrigin=eyJpIjoiYzcxZDlhNWJkNWViNDE2NWEyMWY4NmJiNmY3NGVhMzAiLCJwIjoiaiJ9).
Adds working BiqQuery SQL query for Transformation Queries.
[SUPPORT-5541]: https://keboola.atlassian.net/browse/SUPPORT-5541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add BQ query for Transformation Queries

management/support/index.md
Per Eliska's request, I added the Keboola Support email address and a link to the Keboola Support Portal in case people need to reach Support when logged out of Keboola (unable to use the support form directly within their project).
=> alternative ways of reaching support

components/extractors/other/generic/generic.md
=> Mention generic ex UI

docker-compose.yml
Jira issue(s): https://keboola.atlassian.net/browse/ST-1860
Changes:
- We were using old docker image for AWS cli build. It stopped working after github upgraded Docker version on github actions. Fixing by using official AWS cli image.
=> Build - Use official AWS image

.github/workflows/branch.yml, .github/workflows/main.yml
Jira issue(s): [PROOF-XXX](https://keboola.atlassian.net/browse/ST-1860)
Changes:
- Main failed on https://github.com/keboola/connection-docs/actions/runs/9494842511 
- Found a fix https://florian.ec/blog/github-actions-awscli-errors/
- Test from branch - https://github.com/keboola/connection-docs/actions/runs/9495010883/job/26166418079
=> Fix build #2

components/extractors/communication/email-attachments/index.md
Based on comments in https://keboola.atlassian.net/browse/SUPPORT-8206
Changes:
- Notice about keboola.ex-email-attachments being available only on certain stacks
=> Notice about keboola.ex-email-attachments being available only on certain stacks

components/data-apps/index.md
=> Update data apps default secrets

transformations/index.md, transformations/workspace/index.md
https://keboola.atlassian.net/browse/PST-2453
Remove mentions of MLflow from docs as it's being completely removed form the platform. Spark was also deprecated a long time ago.
=> Remove MLflow (and Spark) mentions

management/index.md
Added Maintenance section at the end of Management page
Changes:
- added section on Maintenance window to Management docs, as we need to reference it Premium SLA addon and MSA
---
Context:
- this is [convo with Najlos](https://keboolaglobal.slack.com/archives/C052Y7MPDL3/p1744007550917509?thread_ts=1742470958.917619&cid=C052Y7MPDL3 ) for context on maintenance window
- this is [convo](https://keboolaglobal.slack.com/archives/C055K9CRFDX/p1745483457099089?thread_ts=1744015311.863859&cid=C055K9CRFDX) where we agreed on including maintenance reference in the docs
=> Add Maintenance section

ai/mcp-server/index.md, management/project/index.md
Project Settings was outdated. Updated and added the context of CLI and MCP Server. 
Storage token changed to keboola api token (as we do not talk about storage token anywhere in the Docs. 
Fixed route to Project Settings in the MCP Server page....
=> Updated Project Settings page 

ai/mcp-server/index.md
This pull request updates the documentation for Keboola's MCP Server to reflect a change in the remote server endpoint and integration URLs. The most important changes ensure consistency across setup instructions, integration guides, and deeplink URLs by replacing references to `/sse` endpoints with `/mcp` endpoints.
**Endpoint and Integration URL Updates:**
* Updated all references in documentation from `https://mcp.<YOUR_REGION>.keboola.com/sse` to `https://mcp.<YOUR_REGION>.keboola.com/mcp` to reflect the new remote server endpoint for MCP Server connections. [[1]](diffhunk://#diff-09f1ce91e95677fbb9fdbc82b6147cb1cab3b93465e99855a3417a3aa89407e9L41-R53) [[2]](diffhunk://#diff-09f1ce91e95677fbb9fdbc82b6147cb1cab3b93465e99855a3417a3aa89407e9L71-R71) …
=> Remove SSE and add streamable http to docs and deeplinks (AI-1402)

404.md, index.md, management/index.md, transformations/python-plain/index.md
Change links from status.keboola.com to keboolastatus.com.
Implements Implements https://keboola.atlassian.net/browse/ST-3331
None.
Multiple link changes
Link URLs
New status page.
Merge & automatic deploy.
Revert of this PR.
None.
=> Update Keboola status links
