keboola/connection-docs

_data/navigation.yml
mergnu az publikuju novy twitter
=> twitter extractor published

.travis.yml, _config.yml, deploy.sh, docker-compose.yml
- custom deploy script
- new service for `aws` command
- delete s3 contents before upload
=> Delete s3 contents before uploading new

extractors/marketing-sales/google-adwords-reports/index.md
noticed by https://keboolasg.zendesk.com/agent/tickets/336
proof: https://github.com/keboola/adwords-extractor/blob/0bef1c5e542ffc56d132c3b69ddebc5c78ae39bb/src/Keboola/AdWordsExtractor/UserStorage.php#L77
=> fix incremental loading mistake

extractors/database/mongodb/index.md, extractors/database/mongodb/mapping.md
=> Few mongodb fixes

_layouts/default.html, _sass/variables.scss, assets/css/style.scss
Same as https://github.com/keboola/developers-docs/pull/76
=> Use webfont loader to prevent FOIT

_data/navigation.yml, management/project/index.md, management/project/migration/index.md
https://github.com/keboola/connection/issues/1341
=> Project migration

management/jobs/index.md
Related to: https://github.com/keboola/kbc-ui/issues/1865
=> Jobs search improved docs

extractors/ip-addresses/index.md, extractors/ip-addresses/kbc-public-ip.json, management/project/index.md
prida info o region a ip adresach ktore som zobral zo zoznamu Elastic IPs v
https://ap-southeast-2.console.aws.amazon.com/vpc/home?region=ap-southeast-2#Addresses:sort=PublicIp
=> add sydney region url and its ips

extractors/ip-addresses/index.md, management/project/index.md
https://keboola.slack.com/archives/CCJAFGS3F/p1537941042000100
=> rename region AUS -> AU

extractors/database/bigquery/index.md
Mel jsem tam jeste preklep v textu
=> bigquery ex - typo writer => extractor

extractors/other/currency-rates/index.md
Related: https://github.com/keboola/curated-data-extractor/issues/7
=> Add UAH currency (toCurrency)

overview/google-data-policy.md
Suvisi s https://github.com/keboola/kbc-ui/issues/3634
=> feat (overview): Google Data Policy

extractors/communication/email-attachments/index.md
update email att ex, fixes #161
=> email attachments update

manipulation/transformations/r/index.md
the link to full list of installed packages goes 404.  Is there another place where packages are added?
=> remove broken link

components/extractors/marketing-sales/google-adwords-reports/index.md
https://keboola.zendesk.com/agent/tickets/12200
=> fix (google-adwords-reports): Added link to setup Google Ads manager account

catalog/index.md
Jira issue https://keboola.atlassian.net/browse/KBC-66
Closed: https://github.com/keboola/connection-docs/pull/193
=> Update info about sharing to specific users

components/extractors/marketing-sales/pipedrive/index.md
doplnil jsem popis k tomu, co jde "company domain".
=> Add explanation of company domain at pipedrive extractor

transformations/python/index.md
=> python 3.8.1

storage/file-uploads/index.md
Updated docs for file upload expiration 
https://status.keboola.com/upcoming-changes-to-file-expiration-in-storage
=> changed file upload expiration

transformations/snowflake/index.md
Add note about clone for tables bigger that 100MB
=> Add note about clone for tables bigger that 100MB

components/extractors/database/sqldb/index.md
Jira: https://keboola.atlassian.net/browse/DOCS-108
Changes:
- Add section about null characters
---
Nech tam je aspon nieco ako sa daju poriesit tie null chars.
=> Add section about null characters

components/extractors/database/sqldb/index.md
Solving - https://keboola.atlassian.net/browse/DOCS-109
=> pgsql extractor - ssl encryption

components/extractors/database/sqldb/index.md
Solving - https://keboola.atlassian.net/browse/DOCS-113
=> mssql extractor - ssl encryption

transformations/python/index.md
=> Update python to version 3.8.5

components/extractors/database/sqldb/index.md
Documentation for tnsnames.ora file for oracle and MySQL Transaction isolation level
=> doc db extractors

_data/navigation.yml, management/jobs/index.md, management/pay-as-you-go/index.md, management/project/limits/index.md, overview/index.md, transformations/index.md, transformations/sandbox/index.md, transformations/synapse/index.md
Dalsi zapracovany / pridany texty z 
https://docs.google.com/document/d/18260ZRhQ-bucY8GA5WxRLEoZ5k8qR1iErsuw2Sq8OIY/edit?usp=sharing
pro Pavla. 
Je v tom i wip stranka pro payg, jen zatim nebude v navigaci.
Diky!
=> Text edits

management/project/tokens/index.md
explicit clarification of tokens & orchestration triggering
already mentioned here https://help.keboola.com/orchestrator/running/#orchestration-execution but the token page is a better place
https://keboola.atlassian.net/browse/PS-872
=> trigger tokens 

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json, management/project/tokens/index.md, overview/index.md
FIXES: https://keboola.atlassian.net/browse/SRE-1226
=> EU Azure stack

management/pay-as-you-go/index.md
Milan jeste doplnil component jobs.
=> Text edits - payg -execution time

index.md
Jira: https://keboola.atlassian.net/browse/DOCS-132
Changes:
- Add link to ideas.keboola.com
---
Toto som slubil, ze pridame, tak nech je to komplet.
=> Add link to ideas.keboola.com

management/project/migration/index.md
transformace nejdou migrovat mezi starýma a novýma transformacema
=> Migration info

_data/navigation.yml, components/extractors/database/azure-storage-table/index.md
Jira: https://keboola.atlassian.net/browse/COM-546
=> Add keboola.ex-azure-storage-table docs

_data/navigation.yml, components/extractors/communication/index.md, components/extractors/database/cosmosdb/index.md, components/extractors/database/index.md, components/extractors/marketing-sales/index.md, components/extractors/other/azure-cost/index.md, components/extractors/other/index.md, components/extractors/social/index.md, components/extractors/storage/index.md, components/writers/bi-tools/index.md, components/writers/bi-tools/looker/index.md, components/writers/bi-tools/thoughtspot/index.md, components/writers/database/index.md, components/writers/storage/index.md
Ahoj, 
prosim zkoukni par dalsich uprav, ktery jsem udelala. Snad to bude vsechno v poradku :-).
Diky moc!
=> minor edits

components/writers/database/snowflake/index.md, management/pay-as-you-go/index.md
Ahoj, jen par drobnosti :-). Diky moc!
=> minor text edits

components/extractors/other/telemetry-data/telemetry-data.md
=> remove wrong event type

components/extractors/other/telemetry-data/telemetry-data.md
=> remove link

transformations/dev-prod-mode/dev-prod-mode.md
=> fixing a link

components/extractors/other/telemetry-data/telemetry-data.md
drobna uprava textu na Matejkysuv request
Dekuju!
=> how to use org mode

components/writers/database/synapse/index.md, transformations/julia/index.md, transformations/openrefine/index.md, transformations/oracle/index.md, transformations/python-plain/index.md, transformations/python/index.md, transformations/r/index.md, transformations/redshift-plain/index.md, transformations/snowflake-plain/index.md, transformations/synapse-plain/index.md
Ahoj, muzes to prosim zkouknout, az budes mit nekdy chvili? 
Dik!
=> proofreading synapse writer, transformations

transformations/index.md
Ahoj, 
Pavel D. chtel k transformacim dopsat, ze jsou automatically versioned. 
Je to takhle prosim te ok?
Dik!
=> automatic versioning

components/extractors/other/telemetry-data/telemetry-data.md
Jira: https://keboola.atlassian.net/browse/KBC-1326
updated list of security events
=> KBC-1326 Update list of events

components/writers/database/mssql/index.md
Jira: https://keboola.atlassian.net/browse/COM-756
Zmena v kode:
https://github.com/keboola/db-writer-mssql/pull/71
=> MsSQL writer - binary types info

management/pay-as-you-go/index.md
Ahoj, Samuel chtel do dokumentace k payg dopsat, ze orchestration jobs nejsou billed. Muzes to prosim zkouknout?
Moc dekuju!
=> payg-orchestration jobs not billed

management/project/limits/index.md
Related to - https://keboola.atlassian.net/browse/SRE-2142
Diskuze - https://keboola.slack.com/archives/CQBEHAXDL/p1620378594118100?thread_ts=1620304405.106500&cid=CQBEHAXDL
=> Data science workspace sizes

_data/navigation.yml, components/branches/index.md, transformations/ml-model-deployment/ml-model-deployment.md, transformations/openrefine/index.md, tutorial/ad-hoc/index.md, tutorial/branches/files-in-branch.md, tutorial/branches/index.md, tutorial/branches/merge-to-production.md, tutorial/branches/prepare-files.md, tutorial/branches/prepare-tables.md, tutorial/branches/project-diff.md, tutorial/branches/tables-in-branch.md, tutorial/index.md
Prolitnes to prosim, az budes mit chvilku? Dekuju!
=> branches - proofreading

transformations/migration/index.md
Jira - https://keboola.atlassian.net/browse/COM-896
=> Update transformation migration docs

components/extractors/other/telemetry-data/telemetry-data.md
Staci takto alebo este je potreba este nieco pridat sem https://help.keboola.com/components/extractors/other/telemetry-data/#security_event
=> Add storage backend audit log events

transformations/variables/index.md
chybely tam vyrenderovane curly brackets
=> Raw mode for curly brackets in code

management/account/index.md
Related to: https://keboola.slack.com/archives/CFVRE56UA/p1628171032070700
Aktualni chovani user session.
=> User session

transformations/index.md, transformations/workspace/index.md
Nevím zda stačí takto nebo jinak. Koukám že teď tam není rozlišeno zda vůbec workspace podporuje "Auto sleep", proto tam píšu i to pokud je to podporováno a zapnuto. Nebo bude lepší nějak více podrobněji?
=> Add info about auto sleep

transformations/mappings/index.md
https://keboola.atlassian.net/browse/PS-2858
Poznamka, ze output-mapping nepodporuje podslozky.
=> PS-2858 Document we don't support subdirectories in OM

transformations/migration/index.md
folder name in transformation migration https://keboola.zendesk.com/agent/tickets/20248
=> Add name of folder in transformation migration

transformations/r-plain/index.md, transformations/r/index.md
Just a slight edit to better reflect reality
=> Fix R version info

components/writers/database/firebolt/index.md
@webrouse had to add his important note.
=> added s3 note

_includes/branches-beta-warning.html, components/branches/index.md, tutorial/branches/index.md
https://keboola.atlassian.net/browse/KBC-1340
=> KBC-1340 General DPM documentation

.github/workflows/branch.yml
Changes:
- Build also PRs targeting main branch
---
Mi nedoslo, ze tam moze niekto poslat PR zvonku :)
=> Build also PRs targeting main branch

management/project/limits/index.md
update of types of backends used for jobs, don't merge before we release the Dynamic backend size Python,R!
=> Update index.md types of backend sizes

storage/files/index.md
Vypadlo z ticketu https://keboola.zendesk.com/agent/tickets/23613
diskuze na slacku https://keboola.slack.com/archives/CQB468K63/p1657800181682779
Limit je na importeru nastavený zde https://github.com/keboola/sapi-importer/blob/4ec316513f6af45525f0153f03556db87662e038/docker/php.ini#L21
=> Update maximum allowed size for uploaded file

management/project/limits/index.md
=> Added price for running ML model

management/project/limits/index.md
FIXES: https://keboola.zendesk.com/agent/tickets/24130
=> Project credits update

components/extractors/other/telemetry-data/telemetry-data.md
Zákazníkům není jasné, jak se počítají agregovaná data pro spotřebu kreditů a dalších limitů. Přidávám k tabulce kbc_usage_metrics_values podrobnější popis, z čeho se jednotlivá čísla skládají.
=> Adding detailed description of usage metric breakdown

components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
Part of: https://keboola.atlassian.net/browse/SRE-3919
Odstranění IPs ze který už nejde žádný traffic. První jsem je smazal úplně ale možná je lepší je tam nechat takhle? Ještě k tomu připravím update na #kbc-news-feed pak.
=> Remove no longer used IPs

transformations/dbt/cli/cli.md, transformations/dbt/cloud/cloud.md, transformations/dbt/flows/flows.md, transformations/dbt/index.md, transformations/dbt/transformation/transformation.md
=> Dbt proofreading

_layouts/default.html
Changes:
- Fix search (new api key + app id)
---
Search uz pojde z indexov co mame pod kontrolou my.
=> Fix search (new api key + app id)

components/applications/triggers/orchestration-trigger-queue-v2/index.md
The Limited access token does not work the same as it did with orchv1. had to update the docs so that it reflects what actually works
=> Update API token instructions

components/extractors/other/telemetry-data/telemetry-data.md
Monika reported some missing info from Telemetry ex docs: https://keboola.slack.com/archives/C02BTQ5JADP/p1669113188394269 I'm filling the missing values to tables description.
=> Adding missing types to job statuses and snowflake query types

management/project/limits/index.md
Máme v produkci billování dbt na multi-tenant stacks. Přidal jsem info do tabulky o spotřebě kreditů a to backend sizes jsem definoval rozdíl mezi Small (běží u nás) a Remote (běží u usera).
=> Adding dbt billing to Project Power

transformations/redshift-plain/index.md, transformations/snowflake-plain/index.md, transformations/snowflake/index.md
jsem to [tady](https://github.com/keboola/connection-docs/pull/404) zvrtal a vsiml jsem si toho az v produkci
=> Move note about RO from legacy snflk transformation to the new one

templates/customer-relationship-management/customer-relationship-management.md, templates/ecommerce/ecommerce.md, templates/google-analytics/google-analytics.md, templates/marketing-platforms/marketing-platforms.md, templates/project-management/project-management.md
=> Fix links in crm and pm templates

management/pay-as-you-go/index.md
Menime pocet free minut mesicne na 60. prosim o merge
=> Update number of free minutes

management/project/users/index.md
is currently available for all stack with qv2 feature
Changes:
- Note about readOnly available
---
=> Edit note about readOnly role

management/pay-as-you-go/index.md
Jira issue(s): https://keboola.atlassian.net/browse/DS-59
Changes:
- Note that PAYG is in Azure NE
- Small typo
---
Bigger update will be done in other PR.
=> Note that PAYG is in Azure NE

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
Related to: https://keboola.slack.com/archives/CL11GKH6H/p1680523469423179
=> missing AZ NE outbound IP

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): PROOF-XXX - not needed
Changes:
- add `auditLog.admin.activation` event to docs
- connection PR here: https://github.com/keboola/connection/pull/4304
- it will affect this page https://help.keboola.com/components/extractors/other/telemetry-data/ 
- locally it looks like this 
- 
---
=> Add auditLog.admin.activation event

storage/tables/index.md
Jira issue(s): https://keboola.atlassian.net/browse/CT-986
Changes:
- add section about incremental loading on table with native datatypes
---
=> add incremental load with native datatypes

storage/tables/data-types/index.md, storage/tables/index.md
Jira issue(s): CT-972
Changes:
- expand native datatypes documentation
---
=> CT-972 Native datatypes docs

components/extractors/marketing-sales/google-analytics/index.md
Changes:
- přidané info o apis které musí být povolený pro správné fungování DATA API
Bylo to tam spíš popsáno pro starší Reporting API. Zrovna to řeším na ZD a takto vypadá že to bude fungovat jak má.
Nevím proč to tam bylo tak různě tučné, tak jsem to spíše všude vyhodil.
=> Google Analytics - custom Oauth

transformations/r/index.md
Changes:
- added note about installing R packages from github
---
slack: https://keboolaglobal.slack.com/archives/C054CKPBU13/p1684755739866199
=> Add note about installing from github

components/extractors/communication/zendesk/index.md
=> Fix broken link in ZD ex rate limits

components/ip-addresses/index.md
Jira issue(s): https://keboola.atlassian.net/browse/ST-388 & https://keboola.atlassian.net/browse/PROOF-52
Changes: 
- Add a note about reverse DNS
=> Add a note about reverse DNS

management/project/limits/index.md
Changes:
- adding DataApps limits for billing in BETA
=> Adding DataApps (beta)

transformations/mappings/index.md
Hi @hhanova, please grammatical review 
Changes:
updated info about read-only input mapping
=> Update info about read-only input mapping

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): https://keboola.atlassian.net/jira/software/projects/SOX/boards/232?selectedIssue=SOX-227
Changes:
- add auditlog events related to SOX feature
---
=> Add events related to protected-branch

components/data-apps/index.md
Changes:
- data-apps - base image section contained link to private repo Dockerfile. Added Dockerfile contents inline with a list of pre-installed packages
=> fix (data-apps): base image info

components/extractors/other/telemetry-data/telemetry-data.md
Changes:
* Slight change of structure (split tables to sections based on selected mode).
* New tables added for AC mode.
* Minor grammar fixes.
I'd like to push it prior proof reading, as SLSP need docs. I'll ask Hanka then to go through the whole telemetry page to fix any issues.
=> Adding docs for Activity Center telemetry ex mode

management/project/limits/index.md
Changes:
fixed the wrong pricing 8 credits to 1 credits.
=> Fix DataApps pricing

_data/navigation.yml, components/extractors/other/hibob/index.md, components/extractors/other/index.md
@hhanova Please check these new docs.
=> add hibob docs

_layouts/default.html
Changes:
- Adds chat bot -- slack https://keboolaglobal.slack.com/archives/C054CKPBU13/p1694175997565549
---
=> ES-68 Add kai chatbot

_layouts/default.html
Reverts keboola/connection-docs#510
Product team wants to remove it.
=> Revert "ES-68 Add kai chatbot"

transformations/mappings/index.md
Jira issue(s): [UT-1046](https://keboola.atlassian.net/browse/UT-1046)
Changes:
- Add warning about native data types table options in input mapping
[UT-1046]: https://keboola.atlassian.net/browse/UT-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add warning about native data types table options in input mapping

_data/navigation.yml, components/extractors/other/hibob/index.md, components/extractors/other/index.md
=> Hibob ex docs

storage/tables/data-types/index.md
Jira issue(s): https://keboola.atlassian.net/browse/PROOF-98
Changes:
-
---
=> SUPPORT-2436 explain the caveant of basetype usage

_data/navigation.yml, components/extractors/marketing-sales/pinterest-ads/index.md
Jira issue(s): [PROOF-100](https://keboola.atlassian.net/browse/PROOF-100)
Pinterest ads documentation
[PROOF-100]: https://keboola.atlassian.net/browse/PROOF-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pinterest Ads docs

_data/navigation.yml, components/extractors/other/index.md, components/extractors/other/weather-api/index.md
Jira issue(s): KCOFAC-2065
Changes:
Added doc for Weather API ex
-
---
=> Add weather-api ex doc

_data/navigation.yml, components/extractors/communication/index.md, components/extractors/communication/ms-outlook/index.md
I don't think Proofreading is necessary here, since it is just copypasta from an already existing documentation.
What we should maybe discuss is the password field that is not used with oAuth.
=> add MS Outlook (Office 365) docs

_data/navigation.yml, components/extractors/other/index.md, components/extractors/other/weather-api/index.md
Jira issue(s): [PROOF-102](https://keboola.atlassian.net/browse/PROOF-102)
[PROOF-102]: https://keboola.atlassian.net/browse/PROOF-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Weather api docs

_data/navigation.yml, components/extractors/erp/index.md, components/extractors/erp/netsuite/index.md
Netsuite ex docs
Jira issue(s): [PROOF-104](https://keboola.atlassian.net/browse/PROOF-104)
[PROOF-104]: https://keboola.atlassian.net/browse/PROOF-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Netsuite docs

components/extractors/other/telemetry-data/telemetry-data.md
New field added to telemetry.
@hhanova Not creating proof task, as it's only one new table row.
=> Adding new job_type field to job telemetry table

components/index.md
Jira issue(s): [PROOF-118](https://keboola.atlassian.net/browse/PROOF-118)
Release stages docs
[PROOF-118]: https://keboola.atlassian.net/browse/PROOF-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release stages documentation draft

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): PROOF-122
Changes:
- There are new events related to SOX and with that we are introducing new column to `security_event` telemetry table.
---
https://keboola.atlassian.net/browse/IR-535
=> Adding two new security events and related columns to the table

storage/tables/data-types/index.md
JIra: https://keboola.atlassian.net/browse/UT-1169
https://keboola.atlassian.net/browse/UT-1169#:~:text=only%20for%20help,new%20filtered%20table.
=> Native types - add one more cons

templates/kai-sql-bot/kai-sql-bot.md
=> fixing incorrect reference on SQL bot docs

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): PROOF-128
Adding additional metrics to Usage Metrics Values table description - metrics related to Buffer API.
Changes:
- BAPI Messages added
- BAPI Receivers added
---
=> Adding BAPI metrics to telemetry docs

_data/navigation.yml, tutorial/ad-hoc/index.md, tutorial/automate/index.md, tutorial/branches/index.md, tutorial/load/database.md, tutorial/load/googlesheets.md, tutorial/load/manual.md, tutorial/manipulate/index.md, tutorial/manipulate/workspace.md, tutorial/write/index.md
fixing numbered lists
shortening titles
moving the Onboarding section to the end of the tutorial
=> numbered lists, parts

tutorial/onboarding/cheat-sheet/index.md, tutorial/onboarding/usage-blueprint/index.md
copyediting and proofreading 
The link for GCP EU is missing.
=> Update documentation 

components/extractors/storage/aws-s3/index.md
Jira issue(s): https://keboola.atlassian.net/browse/GMT-89
Changes:
- Nově nahazujeme credentials pro autentizaci pomocí role v dedikovaném accountu https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3092873220/Preparing+IAM+credentials+for+Keboola+AWS+component
---
=> AWS S3 role AWS account

tutorial/onboarding/governance-guide/index.md
=> Link fixed

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json, overview/index.md
Jira issue(s): https://keboola.atlassian.net/browse/GMT-54
Changes:
- New stack [connection.europe-west3.gcp.keboola.com](https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3144810503/connection.europe-west3.gcp.keboola.com) added
- Related https://github.com/keboola/developers-docs/pull/281
---
=> Add stack - com-keboola-gcp-europe-west3

_data/navigation.yml, components/extractors/marketing-sales/google-dv360/index.md
Jira issue(s): [PROOF-133](https://keboola.atlassian.net/browse/PROOF-133)
DV360 docs
[PROOF-133]: https://keboola.atlassian.net/browse/PROOF-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dv360 docs

transformations/bigquery/index.md
Menší fuckup, tohle tam nepatří.
=> Remove forgotten line

storage/tables/data-types/index.md
Jira issue(s): PROOF-148
Changes:
-
---
=> SUPPORT-4195 Explain how to work around the issue of incorrect type from basetype

tutorial/onboarding/architecture-guide/index.md
MPS changed to MPA (Multi-project architecture)
Changes:
-
---
=> Misspelled abbreviation fixed

tutorial/onboarding/index.md
there were still some links to internal Conflu. These have been replaced by the correct ones.
Changes:
-
---
=> Fix of the links

storage/byodb/external-buckets/index.md
Jira issue(s): PROOF-166
Changes:
---
=> Add text about eb table names limit

_data/navigation.yml, components/extractors/marketing-sales/index.md, components/extractors/marketing-sales/zoho/index.md
Zoho docs added
Jira issue(s): PROOF-169 https://keboola.atlassian.net/browse/PROOF-169
=> add zoho docs

storage/byodb/external-buckets/index.md
https://github.com/keboola/connection/pull/4876#issuecomment-1976218983
=> External bucket limitation

storage/byodb/external-buckets/index.md
=> dataset has _ not -

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json, overview/index.md
Jira issue(s): https://keboola.atlassian.net/browse/GMT-185
Changes:
- New stack [https://connection.us-east4.gcp.keboola.com/](https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3199762479/connection.us-east4.gcp.keboola.com) added
- Related https://github.com/keboola/developers-docs/pull/288
---
https://console.cloud.google.com/net-services/nat/details/us-east4/com-keboola-gcp-us-east4-main/com-keboola-gcp-us-east4-main?project=com-keboola-gcp-us-east4&supportedpurview=project&tab=details
=> Add stack com-keboola-gcp-us-east4

storage/byodb/external-buckets/index.md
Jira issue(s):  https://keboola.atlassian.net/browse/PROOF-185
Changes:
- add information about read only and external buckets limitation in snowflake
---
=> readOnly access with external buckets has a limitation alert

storage/byodb/external-buckets/index.md
Jira issue(s): CT-1325
Changes:
-  <img width="1051" alt="Screenshot 2024-03-22 at 8 02 15" src="https://github.com/keboola/connection-docs/assets/6448364/131cd02b-775d-4c8c-9b1d-967f62c8544a">
---
=> CT-1325 add info about snapshot and ex bucket

storage/tables/data-types/index.md
https://keboola.atlassian.net/browse/CT-1301
=> CT-1301 Update NUMBER(38,0)

storage/byodb/external-buckets/index.md
Jira: [BIG-244](https://keboola.atlassian.net/browse/BIG-244)
Driver: https://github.com/keboola/php-storage-driver-bigquery/pull/129
Tests: https://github.com/keboola/storage-api-php-client/pull/1313
Changes:
-
---
[BIG-244]: https://keboola.atlassian.net/browse/BIG-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> info about we suport only big lake external table

overview/index.md, transformations/index.md
=> Pavel synek patch 1

transformations/index.md
proofread, edited, added a link for read-only input mapping
Thanks!
=> Proofread and add a link

components/extractors/storage/aws-s3/index.md
FIXES: https://keboola.atlassian.net/browse/ST-1584
- Povoleni `keboola.ex-aws-s3` pro https://connection.us-east4.gcp.keboola.com/
=> keboola.ex-aws-s3 - GCP multi-tenants

transformations/ml-model-deployment/index.md
Please merge after approval :-)
Thank you!
=> updated a link

components/writers/database/snowflake/index.md
Please merge after approval. Thank you!
=> Docs 335 remove power bi from qlick step

storage/byodb/external-buckets/index.md
Jira issue(s): https://keboola.atlassian.net/browse/PROOF-214
Jira: https://keboola.atlassian.net/browse/BIG-253
Changes:
- document specifics on biglake tables in bigquery
---
=> BIG-253 document biglake tables

_data/navigation.yml, storage/byodb/external-buckets/index.md
=> Updating external buckets

components/index.md
Jira issue(s): [PROOF-225](https://keboola.atlassian.net/browse/PROOF-225)
Changes:
- Fixed screenshot link
[PROOF-225]: https://keboola.atlassian.net/browse/PROOF-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAB-123 Docs - Fixed screenshot link

_data/navigation.yml, management/telemetry/telemetry-dashboards/telemetry-dashboards.md
add management/telemetry to navigation
=> Add telemetry to management

components/extractors/other/telemetry-data/telemetry-data.md, management/project/limits/index.md
Do telemetrie přibylo info o nových typech PPU, které využívají někteří zákazníci: https://changelog.keboola.com/telemetry-update-new-ppu-field/
Doplňuji do dokumentace jak je kreditům, tak to telemetry ex.
Jira issue(s): [PROOF-233](https://keboola.atlassian.net/browse/PROOF-233)
[PROOF-233]: https://keboola.atlassian.net/browse/PROOF-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding new PPU types to Time Credits and Telemetry ex docs

components/data-apps/index.md
=> Update index.md - example data apps - fixed links

.github/workflows/branch.yml, .github/workflows/main.yml
=> docker-compose => docker compose

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): PROOF-251
We have created a  new table and enriched existing table with new column to offer useful telemetry data for our customers. 
Changes:
Adding new kbc_file_event  table and new column in kbc_component_configuration table 
-
---
=> feat:new kbc_file_event tbl & col to comp_config

storage/byodb/external-buckets/index.md
=> Snowflake sharing update

management/project/users/index.md
Changes:
- Fix limitations of guest role
---
The limitations of guest role applied for projects on Queue v1.
In the UI, the ext. auth is still disabled.
=> Fix limitations of guest role

storage/byodb/external-buckets/index.md
Jira issue(s):   https://keboola.atlassian.net/browse/PROOF-260
Changes:
- based on [this](https://keboolaglobal.slack.com/archives/C06U9V72PEF/p1724420184595839) discussion and this [PR](https://github.com/keboola/connection-docs/pull/648) 
---
=> Few fixes of docs about external dataset sharing

storage/data-streams/data-streams.md
=> data streams - changed pricing

storage/data-streams/data-streams.md
=> fixed typos

management/pay-as-you-go/index.md
Changes:
- adding note about dataRetentionInDays=0 for PAYG -> https://keboolaglobal.slack.com/archives/C014EQD3RQE/p1728995290921469
---
=> Zero dataRetention for payg

transformations/bigquery/index.md
Jira issue(s):  https://keboola.atlassian.net/browse/PROOF-287
Changes:
- note about UDFs - they have to be TEMP
---
=> Document BQ UDFs

storage/tables/data-types/index.md
Jira issue(s): -
Changes:
JIRA : [CT-1820](https://keboola.atlassian.net/browse/CT-1820)
- NUMBER(38,0) is considered as INTEGER basetype
---
[CT-1820]: https://keboola.atlassian.net/browse/CT-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NUMBER(38,0) is considered as INTEGER basetype

components/extractors/database/mongodb/index.md
Jira issue(s): [PROOF-299](https://keboola.atlassian.net/browse/PROOF-299)
Changes:
- addition of incremental fetching description
---
[PROOF-299]: https://keboola.atlassian.net/browse/PROOF-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> mongodb docs fix -> incremental fetching

components/extractors/marketing-sales/criteo/index.md
https://keboola.atlassian.net/browse/SUPPORT-9386
=> Added link to Criteo API documentation

components/data-apps/general-design-guide/index.md
=> update path to files in repository of data app

components/extractors/other/google-search-console/index.md
[https://keboola.atlassian.net/browse/CFT-3065](https://keboola.atlassian.net/browse/CFT-3065)
Update user documentation to correspond with developer documentation.
=> update how to fill domain

components/extractors/other/telemetry-data/telemetry-data.md
Jira issue(s): [PROOF-XXX](https://keboola.atlassian.net/browse/PROOF-313)
Changes:
2 tables about data apps which are going to be available for customers of AC.
=> feat:adding data app tables AC

storage/byodb/snowflake-secure-data-sharing/index.md
=> Added beta infobox

components/data-apps/index.md
Jira issue(s): [PST-2285](https://keboola.atlassian.net/browse/PST-2285)
Changes:
- updated [Data App base image](https://help.keboola.com/components/data-apps/#base-image) content. (It wasn't up to date)
[PST-2285]: https://keboola.atlassian.net/browse/PST-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (data-apps): update base image

components/extractors/other/telemetry-data/telemetry-data.md
He there is just small change in the documentation
Jira issue(s): [PROOF-XXX](https://keboola.atlassian.net/browse/PROOF-327)
thank you
=> feat:adding usage breakdown

components/extractors/database/index.md, components/extractors/database/oracle/index.md
https://keboola.atlassian.net/browse/SUPPORT-9862
=> hidden the Log-based CDC

components/extractors/database/mysql/index.md
Remove public beta from mysql cdc
=> remove public beta warning from mysql cdc

storage/tables/data-types/index.md
=> Minor edits - native data types

storage/tables/data-types/index.md
=> Fix warning in data types

components/extractors/other/telemetry-data/telemetry-data.md, storage/data-streams/data-streams.md
Jira issue(s): [PROOF-349](https://keboola.atlassian.net/browse/PROOF-349)
Changes:
- BufferAPI is no longer available
---
[PROOF-349]: https://keboola.atlassian.net/browse/PROOF-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Stream API is in place for Data streams

components/extractors/other/telemetry-data/telemetry-data.md
i I would like to ask for approve of small chenges in documentation
[Jira issue(s): PROOF-XXX](https://keboola.atlassian.net/browse/PROOF-350)
thanks
=> fix: Clarifying the description about configuration rows

storage/tables/data-types/index.md
updated the part about handling nulls
=> update native data types

storage/tables/data-types/index.md
please review and merge @hhanova
=> Native data types - label behaviour change

components/extractors/other/telemetry-data/telemetry-data.md
https://keboola.atlassian.net/browse/CT-1926
https://github.com/keboola/connection/pull/5449
There is new audit log event in connection auditLog.storageBackendConnection.detail
=> Add audit log event auditLog.storageBackendConnection.detail

management/project/limits/index.md
I just made a small change in the documentation regarding Snowpark billing, just for clarification and better understanding.
https://keboola.atlassian.net/jira/core/projects/PROOF/board?selectedIssue=PROOF-361
thanks
=> feat: adding snowpark billing note

storage/data-streams/data-streams.md
=> Update data-streams pricing info

storage/tables/data-types/index.md
=> fix native types labeling

components/data-apps/index.md
=> Update index.md - adding info about the new feature - upload secrets.toml

management/project/limits/index.md
ML flow not available therefore deleting it from a price list
=> Remove ML flow from pricing table

flows/index.md
=> fixed permalink to AI Flow Builder

flows/ai-flow-builder/index.md, flows/index.md
=> Fix of the permalinks in Flows

transformations/mappings/index.md
=> Added the Delete Rows from Transformation table feature

components/extractors/other/telemetry-data/telemetry-data.md
just small chnages in our documentation
=> Update telemetry-datashare owner column

storage/byodb.md
Jira issue(s): SUPPORT-11507
Changes:
- clarified how the project id should be inserted into the read only role template
=> SUPPORT-11507 Clarify how roles are named

management/notifications/notifications.md
=> Fixed bullet points in Notifications chapter

_layouts/default.html
Prefill env checkbox to collect URL from which feedback through Atlassian issue collector was submitted.
=> Prefill env checkbox to collect URL

components/extractors/other/telemetry-data/telemetry-data.md
small change in description of the flow-column in kbc_job table
=> fix: kbc_job flow description change

management/project/limits/index.md, transformations/python-plain/index.md, transformations/r-plain/index.md
3 changes:
- PYthon transformation - I think it is fair to cross reference its implications on credit consumption
- R transformations - Dynamic backends were missing, so I added the same text, a picture is omitted on purpose as it is not needed
- changed the new credit for Data Scienece jobs and workspaces, I finally added there a date temprarily, to show it is already updated
=> Credits for Data Science update (and cross referenced in our Documentation)

components/data-apps/index.md
Changes:
- Change Base Image of Streamlit data apps to contain keboola.component library
---
=> feat: Add keboola.component library into docker base image for streamlit

ai/mcp-server/index.md
=> Discord link removed

management/pay-as-you-go/index.md
I updated the PAYG pricing section to better describe how monthly recharge of free credits work.
=> Clarify PAYG free credits

components/extractors/index.md, management/jobs/index.md, storage/index.md, transformations/python/index.md, transformations/workspace/index.md
Added a youtube link to storage.
Changes:
-
---
=> Added a link to the Storage section

storage/byodb/external-buckets/index.md
Changes:
- external buckets are now allowed in input mapping
---
https://keboola.atlassian.net/browse/DMD-67
=> DMD-67 - External buckets are now allowed in Input Mapping

storage/byodb/external-buckets/index.md
Update of external datasets in IM - disableable by support.
=> ED in IM update

components/extractors/other/telemetry-data/telemetry-data.md
Updating the docs relevant to recent changes announced in changelog: https://changelog.keboola.com/telemetry-update-flow-id-and-name-in-kbc-job-table/
=> Update to kbc_job telemetry data info

_data/navigation.yml, flows/conditional-flows/index.md
Documentation updated for the Conditional Flows + fixed the bug by adding the page into the Menu....
https://keboola.atlassian.net/browse/AJDA-568
https://docs.google.com/document/d/1d-aWu7xTdyNRC4n7L1SqLvIoieSsA9ppxGvBHxMuZJs/edit?tab=t.0
=> Conditional flows

components/extractors/other/telemetry-data/telemetry-data.md
prosim palec hore, iba popisek k tym korekciam v data app a ds sandboxoch. dik
=> feat: note about clearing values

ai/mcp-server/index.md
Now contains detailed client integration instructions and available stack URLs for Cursor, Windsurf, and VS Code.
=> Enhance MCP Server documentation 

ai/index.md
deleted mention about AI flow builder
Changes:
-
---
=> deleted mention about AI flow builder

transformations/workspace/index.md
Adding guide about private key encryption to our docs to help users storing the keys on local machines. Related support ticket: https://keboola.atlassian.net/browse/SUPPORT-12622
=> Private key encryption guide

components/extractors/other/telemetry-data/telemetry-data.md
Changes:
-
---
new event has been introduced in https://github.com/keboola/connection/pull/6094, so it has to be documented
=> add new auditlog event

components/extractors/ip-addresses/kbc-public-ip.json, components/ip-addresses/index.md, components/ip-addresses/kbc-public-ip.json
Jira: https://keboola.atlassian.net/browse/AJDA-337
Changes:
- Remove Queue v1 and Syrup mentions
=> Remove Syrup and Queue v1

catalog/index.md
Jira issue(s): [DMD-78](https://keboola.atlassian.net/jira/software/projects/DMD/boards/506?assignee=712020%3A948ae21b-07f2-4820-adf4-81752783b0c6&selectedIssue=DMD-78)
Changes:
Update of documentation to reflect new functionality in Data Catalog based on new features / edit in data sharing. 
TODO: screenshots still needs to be updated
[DMD-78]: https://keboola.atlassian.net/browse/DMD-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update documentation to reflect new functionality in Data Catalog

management/pay-as-you-go/index.md
https://keboola.atlassian.net/browse/SUPPORT-13505
=> Fixed wording about BYODB in PAYG

components/extractors/other/telemetry-data/telemetry-data.md
workspace schema in our telemety data (kbc_workspace table)
=> feat: Add workspace_schema field to telemetry-data
